name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package
        run: zip -r starter.zip . -x '*.git*'

      - name: Push release
        uses: softprops/action-gh-release@v2
        with:
          files: starter.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
